INSERT INTO `t_checkgroup` VALUES ('2', '0002', '视力色觉', 'SLSJ', '0', '视力色觉', null);
INSERT INTO `t_checkgroup` VALUES ('3', '0003', '血常规', 'XCG', '0', '血常规', null);
INSERT INTO `t_checkgroup` VALUES ('4', '0004', '尿常规', 'NCG', '0', '尿常规', null);
INSERT INTO `t_checkgroup` VALUES ('5', '0005', '肝功三项', 'GGSX', '0', '肝功三项', null);
INSERT INTO `t_checkgroup` VALUES ('6', '0006', '肾功三项', 'NGSX', '0', '肾功三项', null);
INSERT INTO `t_checkgroup` VALUES ('7', '0007', '血脂四项', 'XZSX', '0', '血脂四项', null);
INSERT INTO `t_checkgroup` VALUES ('8', '0008', '心肌酶三项', 'XJMSX', '0', '心肌酶三项', null);
INSERT INTO `t_checkgroup` VALUES ('9', '0009', '甲功三项', 'JGSX', '0', '甲功三项', null);
INSERT INTO `t_checkgroup` VALUES ('10', '0010', '子宫附件彩超', 'ZGFJCC', '2', '子宫附件彩超', null);
INSERT INTO `t_checkgroup` VALUES ('11', '0011', '胆红素三项', 'DHSSX', '0', '胆红素三项', null);

-- ----------------------------
-- Records of t_checkgroup_checkitem
-- ----------------------------

INSERT INTO `t_checkgroup_checkitem` VALUES ('2', '6');
INSERT INTO `t_checkgroup_checkitem` VALUES ('2', '7');
INSERT INTO `t_checkgroup_checkitem` VALUES ('2', '8');
INSERT INTO `t_checkgroup_checkitem` VALUES ('2', '9');
INSERT INTO `t_checkgroup_checkitem` VALUES ('2', '10');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '11');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '12');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '13');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '14');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '15');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '16');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '17');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '18');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '19');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '20');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '21');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '22');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '23');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '24');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '25');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '26');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '27');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '28');
INSERT INTO `t_checkgroup_checkitem` VALUES ('3', '29');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '30');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '31');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '32');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '33');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '34');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '35');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '36');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '37');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '38');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '39');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '40');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '41');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '42');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '43');
INSERT INTO `t_checkgroup_checkitem` VALUES ('4', '44');
INSERT INTO `t_checkgroup_checkitem` VALUES ('5', '45');
INSERT INTO `t_checkgroup_checkitem` VALUES ('5', '46');
INSERT INTO `t_checkgroup_checkitem` VALUES ('5', '47');
INSERT INTO `t_checkgroup_checkitem` VALUES ('6', '48');
INSERT INTO `t_checkgroup_checkitem` VALUES ('6', '49');
INSERT INTO `t_checkgroup_checkitem` VALUES ('6', '50');
INSERT INTO `t_checkgroup_checkitem` VALUES ('7', '51');
INSERT INTO `t_checkgroup_checkitem` VALUES ('7', '52');
INSERT INTO `t_checkgroup_checkitem` VALUES ('7', '53');
INSERT INTO `t_checkgroup_checkitem` VALUES ('7', '54');
INSERT INTO `t_checkgroup_checkitem` VALUES ('8', '55');
INSERT INTO `t_checkgroup_checkitem` VALUES ('8', '56');
INSERT INTO `t_checkgroup_checkitem` VALUES ('8', '57');
INSERT INTO `t_checkgroup_checkitem` VALUES ('9', '58');
INSERT INTO `t_checkgroup_checkitem` VALUES ('9', '59');
INSERT INTO `t_checkgroup_checkitem` VALUES ('9', '60');
INSERT INTO `t_checkgroup_checkitem` VALUES ('10', '61');
INSERT INTO `t_checkgroup_checkitem` VALUES ('10', '62');
INSERT INTO `t_checkgroup_checkitem` VALUES ('11', '63');
INSERT INTO `t_checkgroup_checkitem` VALUES ('11', '64');
INSERT INTO `t_checkgroup_checkitem` VALUES ('11', '65');